# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

jobs:

  lint:
    docker:
      # specify the version you desire here
      - image: circleci/node:8-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn install
      - run: yarn lint
      - run: yarn docs

  test-unit:
    docker:
      # specify the version you desire here
      - image: circleci/node:8-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn install
      - run: yarn test:unit
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  test-integration:
    docker:
      # specify the version you desire here
      - image: circleci/node:8-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: Xvfb :98 &
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: xvfb-run -a yarn test:render

  test-acceptance:
    docker:
      # specify the version you desire here
      - image: circleci/node:8-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: Xvfb :98 &
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: xvfb-run -a yarn test:e2e

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      - test-unit
      - test-integration
